logger:
  logger_level: debug
  logger_development: true

grpc:
  host: "localhost"
  port: 8082

storage:
#  migration: "/etc/migrations"
  migration: "migrations"

database:
  host: "localhost"
  port: 5432
  dbname: "postgres"
  username: "postgres"
  password: "postgres"

rmq:
  uri: "amqp://guest:guest@localhost:5672/"
  reConnect:
    maxElapsedTime: "1m"
    initialInterval: "1s"
    multiplier: 2
    maxInterval: "15s"

queues:
  events:
    exchangeName: "events"
    exchangeType: "fanout"
    queueName: "notifications"
    bindingKey: ""

consumer:
  consumerTag: "banner_notifications"
  qosPrefetchCount: 10
  threads: 4